#!/usr/bin/env node
/** Lista e carrega somente research local indexado pela especificação. */
import { existsSync, lstatSync, statSync } from "node:fs";
import { readFile, readdir } from "node:fs/promises";
import { basename, dirname, relative, resolve, sep } from "node:path";

const args = process.argv.slice(2); const specInput = args.find((arg) => !arg.startsWith("--")); const json = args.includes("--json"); const emit = args.includes("--emit-content"); const maxBytes = Number(args.includes("--max-bytes") ? args[args.indexOf("--max-bytes") + 1] : 65536);
const inside = (path, root) => path === root || path.startsWith(`${root}${sep}`);
const slugify = (value) => value.normalize("NFKC").toLocaleLowerCase().trim().replace(/[^\p{L}\p{N}\s_-]/gu, "").replace(/[\s-]+/gu, "-").replace(/^-+|-+$/gu, "");
function section(text, title) { return text.match(new RegExp(`^####\\s+${title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$\\n([\\s\\S]*?)(?=^####\\s+|^###\\s+|$)`, "m"))?.[1] ?? ""; }
async function files(path) { if (!existsSync(path)) return []; const stat = lstatSync(path); if (!stat.isDirectory()) return [path]; const children = await readdir(path, { withFileTypes: true }); return (await Promise.all(children.map((entry) => files(resolve(path, entry.name))))).flat(); }
async function anchors(path) { try { const text = await readFile(path, "utf8"); const counts = new Map(); return new Set([...text.matchAll(/^#{1,6}\s+(.+?)\s*#*\s*$/gm)].map((match) => { const base = slugify(match[1]); const count = counts.get(base) ?? 0; counts.set(base, count + 1); return count ? `${base}-${count}` : base; })); } catch { return new Set(); } }
if (!specInput || !existsSync(specInput) || !Number.isInteger(maxBytes) || maxBytes <= 0) { console.error("ERRO: spec inexistente ou max-bytes inválido."); process.exitCode = 2; }
else {
  const spec = resolve(specInput); const text = await readFile(spec, "utf8"); const root = (() => { let current = dirname(spec); while (basename(current) !== "specs" && dirname(current) !== current) current = dirname(current); return basename(current) === "specs" ? dirname(current) : dirname(dirname(spec)); })(); const research = resolve(dirname(spec), "research"); const indexed = [...new Set([...section(text, "Artefatos de pesquisa armazenados").matchAll(/`([^`]*research\/[^`]*)`/g)].map((match) => match[1]))].sort(); const errors = []; const artifacts = []; const seen = new Set();
  for (const raw of indexed) { const candidate = resolve(root, raw); if (!inside(candidate, research) || !existsSync(candidate) || lstatSync(candidate).isSymbolicLink()) { errors.push(`caminho inseguro ou symlink: ${raw}`); continue; } for (const path of await files(candidate)) { const real = resolve(path); if (seen.has(real)) continue; seen.add(real); if (!inside(real, research) || !lstatSync(real).isFile() || lstatSync(real).isSymbolicLink()) { errors.push(`artefato inexistente ou inseguro: ${path}`); continue; } const size = statSync(real).size; const item = { path: relative(root, real).replaceAll("\\", "/"), bytes: size, truncated: size > maxBytes }; if (emit) { const buffer = await readFile(real); try { item.content = new TextDecoder("utf-8", { fatal: true }).decode(buffer.subarray(0, maxBytes)); } catch { errors.push(`artefato não textual: ${item.path}`); item.content = ""; } } artifacts.push(item); } }
  const claims = []; const budgets = []; const critical = []; const claimRe = /^-\s+\*\*(R-\d{3,})\*\*\s+\[(critical|high|medium|low)\]\s+(.+?)\s+[—-]\s+Verdict:\s+(verified|refuted|unverifiable)\s+[—-]\s+Confidence:\s+(high|medium|low)\s+[—-]\s+Evidence:\s+(\S+)\s+[—-]\s+Budget:\s+(\d+\/\d+)\.?\s*$/gmi;
  for (const match of section(text, "Researchs executados").matchAll(claimRe)) { const claim = { id: match[1], criticality: match[2].toLowerCase(), claim: match[3], verdict: match[4].toLowerCase(), confidence: match[5].toLowerCase(), evidence: match[6], budget: match[7] }; claims.push(claim); const [file, anchor] = claim.evidence.split("#"); const evidence = resolve(dirname(spec), file); if (!inside(evidence, research) || !existsSync(evidence) || lstatSync(evidence).isSymbolicLink()) errors.push(`${claim.id}: evidence local inexistente ou insegura: ${file}`); else if (anchor && !(await anchors(evidence)).has(anchor)) errors.push(`${claim.id}: âncora inexistente na evidence: #${anchor}`); const [used, limit] = claim.budget.split("/").map(Number); budgets.push([used, limit]); if (!limit || used > limit) errors.push(`${claim.id}: orçamento ${!limit ? "inválido" : "excedido"} (${used}/${limit})`); if (claim.criticality === "critical" && claim.verdict !== "verified") critical.push(`${claim.id}: critical claim não verificado (${claim.verdict})`); }
  const counts = new Map(); claims.forEach((claim) => counts.set(claim.id, (counts.get(claim.id) ?? 0) + 1)); counts.forEach((count, id) => { if (count > 1) errors.push(`${id}: ID duplicado`); }); const limits = new Set(budgets.map(([, limit]) => limit)); if (limits.size > 1) errors.push("claims possuem limites de orçamento divergentes"); else if (budgets.length && budgets.reduce((total, [used]) => total + used, 0) > budgets[0][1]) errors.push(`orçamento total excedido (${budgets.reduce((total, [used]) => total + used, 0)}/${budgets[0][1]})`); if (text.includes("[critical]") && !claims.length) errors.push("critical claim não segue o contrato ResearchClaim"); errors.push(...critical); if (!indexed.length) errors.push("nenhum artefato de research indexado"); const payload = { schema_version: 1, result: errors.length ? "failed" : "passed", artifacts, claims, errors };
  if (json) console.log(JSON.stringify(payload, null, 2)); else { console.log(`Research: ${payload.result.toUpperCase()}`); artifacts.forEach((item) => console.log(`- ${item.path}: ${item.bytes} bytes${item.truncated ? " (truncado)" : ""}`)); errors.forEach((error) => console.log(`ERRO: ${error}`)); } process.exitCode = payload.result === "passed" ? 0 : 1;
}
