#!/usr/bin/env node
/** Compara IDs definidos em spec.md com marcadores presentes nos testes. */
import { existsSync } from "node:fs";
import { readFile, readdir } from "node:fs/promises";
import { extname, join, relative, resolve } from "node:path";

const skipped = new Set([".agents", ".git", ".hg", ".svn", ".venv", "build", "coverage", "dist", "examples", "fixture", "fixtures", "node_modules", "research", "samples", "target", "vendor"]);
const extensions = new Set([".cs", ".go", ".java", ".js", ".jsx", ".kt", ".php", ".py", ".rb", ".rs", ".ts", ".tsx"]);
async function walk(directory) { const files = []; for (const item of await readdir(directory, { withFileTypes: true })) { if (skipped.has(item.name)) continue; const path = join(directory, item.name); if (item.isDirectory()) files.push(...await walk(path)); else files.push(path); } return files; }
const args = process.argv.slice(2); const positional = args.filter((arg) => !arg.startsWith("--") && !/^\d+$/.test(arg)); const [spec, root] = positional;
const option = (name, fallback) => args.includes(name) ? args[args.indexOf(name) + 1] : fallback;
const kinds = option("--kinds", "US,FR,NFR,AC").split(",").map((item) => item.trim().toUpperCase()).filter(Boolean); const minimum = Number(option("--minimum-tests", "3")); const json = args.includes("--json"); const fullChain = args.includes("--full-chain");
if (!spec || !root || !existsSync(spec) || !existsSync(root) || !Number.isInteger(minimum) || minimum < 1 || kinds.some((kind) => !["US", "FR", "NFR", "AC"].includes(kind))) { console.error("ERRO: spec, raiz de testes, tipos ou mínimo inválidos."); process.exitCode = 2; }
else {
  const specPath = resolve(spec); const rootPath = resolve(root); const text = await readFile(specPath, "utf8");
  const definitions = { US: [...text.matchAll(/^#{4,6}\s+(US-\d{3,})\b/gm)].map((m) => m[1]), AC: [...text.matchAll(/^#{4,6}\s+(AC-\d{3,})\b/gm)].map((m) => m[1]), FR: [...text.matchAll(/^\s*-\s+\*\*(FR-\d{3,})\*\*\s*:/gm)].map((m) => m[1]), NFR: [...text.matchAll(/^\s*-\s+\*\*(NFR-\d{3,})\*\*\s*:/gm)].map((m) => m[1]) };
  const required = new Set(kinds.flatMap((kind) => definitions[kind])); const allDefined = new Set(Object.values(definitions).flat()); const locations = {}; const records = []; const files = (await walk(rootPath)).filter((path) => { const rel = relative(rootPath, path).toLowerCase(); const name = rel.split("/").pop(); return extensions.has(extname(path).toLowerCase()) && (/(^|\/)tests?(\/|$)|(^|\/)spec(\/|$)/.test(rel) || name.startsWith("test_") || name.includes(".test.") || name.includes(".spec.") || name.endsWith("_test.py") || name.endsWith("_test.go")); });
  for (const file of files) { let content; try { content = await readFile(file, "utf8"); } catch { continue; } content.split(/\r?\n/).forEach((line, index) => { const marked = new Set(); const marker = line.match(/SPECSFY\s*:\s*(.*)$/i); if (marker) for (const id of marker[1].matchAll(/\b(?:US|AC|FR|NFR)-\d{3,}\b/g)) marked.add(id[0]); for (const tag of line.matchAll(/@((?:US|AC|FR|NFR)-\d{3,})\b/g)) marked.add(tag[1]); if (marked.size) { const location = `${relative(rootPath, file).replaceAll("\\", "/")}:${index + 1}`; records.push([...marked]); for (const id of marked) (locations[id] ??= []).push(location); } }); }
  const counts = Object.fromEntries([...required].sort().map((id) => [id, (locations[id] ?? []).length])); const insufficient = Object.fromEntries(Object.entries(counts).filter(([id, count]) => count < (id.startsWith("AC-") ? 1 : minimum)).map(([id, count]) => [id, (id.startsWith("AC-") ? 1 : minimum) - count])); const uncovered = [...required].filter((id) => !(id in locations)).sort(); const featureCases = records.filter((marked) => marked.some((id) => allDefined.has(id))).length; const featureMissing = Math.max(0, minimum - featureCases); const orphan = Object.keys(locations).filter((id) => !allDefined.has(id)).sort();
  const taskLocations = {}; for (const match of text.matchAll(/^- \[[ xX]\] (T\d{3,})\b.+?[—-] Refs: (.+?) [—-] Depends:/gm)) for (const id of match[2].matchAll(/\b(?:US|AC|FR|NFR)-\d{3,}\b/g)) (taskLocations[id[0]] ??= []).push(match[1]); const evidenceLocations = {}; const evidenceErrors = []; for (const match of text.matchAll(/^\s*<!--\s*specsfy:evidence\s+(\{.*?\})\s*-->\s*$/gm)) { try { const item = JSON.parse(match[1]); if (typeof item.task !== "string" || !Array.isArray(item.refs)) evidenceErrors.push("evidence sem task/refs válidos"); else item.refs.filter((id) => typeof id === "string").forEach((id) => (evidenceLocations[id] ??= []).push(item.task)); } catch (error) { evidenceErrors.push(`JSON inválido: ${error.message}`); } }
  const broken = fullChain ? [...required].sort().flatMap((id) => { const missing = []; if (id in insufficient) missing.push(counts[id] ? `test-cases:${insufficient[id]}` : "test"); if (!(id in taskLocations)) missing.push("task"); if (!(id in evidenceLocations)) missing.push("evidence"); return missing.length ? [{ id, missing }] : []; }).concat(evidenceErrors.map((message) => ({ id: "evidence", missing: [message] }))) : [];
  const result = { spec: specPath, root: rootPath, kinds, files_scanned: files.length, required_cases: minimum, feature_cases: featureCases, feature_cases_missing: featureMissing, required: required.size, covered: [...required].filter((id) => id in locations).length, uncovered, case_counts: counts, insufficient_cases: insufficient, orphan_markers: orphan, task_locations: taskLocations, evidence_locations: evidenceLocations, broken_chains: broken, locations };
  if (json) console.log(JSON.stringify(result, null, 2)); else { console.log(`Rastreabilidade: ${result.covered}/${result.required} IDs cobertos em ${files.length} arquivos de teste.`); if (uncovered.length) console.log(`SEM TESTE: ${uncovered.join(", ")}`); Object.entries(insufficient).forEach(([id, value]) => console.log(`CASOS TDD INSUFICIENTES ${id}: ${counts[id]}/${id.startsWith("AC-") ? 1 : minimum} (faltam ${value})`)); if (featureMissing) console.log(`CASOS TDD INSUFICIENTES FEATURE: ${featureCases}/${minimum} (faltam ${featureMissing})`); if (orphan.length) console.log(`MARCADORES ÓRFÃOS: ${orphan.join(", ")}`); broken.forEach((item) => console.log(`CADEIA QUEBRADA ${item.id}: ${item.missing.join(", ")}`)); console.log(Object.keys(insufficient).length || featureMissing || orphan.length || broken.length ? "RESULTADO: GAPS" : "RESULTADO: OK"); }
  process.exitCode = Object.keys(insufficient).length || featureMissing || orphan.length || broken.length ? 1 : 0;
}
