#!/usr/bin/env node
/** Consolida o progresso do Specsfy sem alterar o estado do repositório. */
import { existsSync } from "node:fs";
import { readFile, readdir } from "node:fs/promises";
import { join, resolve } from "node:path";

const folders = ["draft", "defined", "planned", "in-progress", "review", "completed"];
const args = process.argv.slice(2); const root = resolve(args.find((item) => !item.startsWith("--")) ?? "."); const slug = args.includes("--slug") ? args[args.indexOf("--slug") + 1] : undefined; const json = args.includes("--json");
const metric = (complete, total) => ({ complete, total, percent: total ? Math.round(complete / total * 1000) / 10 : 0 });
async function specsIn(directory) { if (!existsSync(directory)) return []; const entries = await readdir(directory, { withFileTypes: true }); return entries.filter((entry) => entry.isDirectory() && existsSync(join(directory, entry.name, "spec.md"))).map((entry) => join(directory, entry.name, "spec.md")); }
let paths = (await Promise.all(folders.map((folder) => specsIn(join(root, "specs", folder)))).then((sets) => sets.flat())).concat(await specsIn(join(root, "specs", "specs"))); paths = [...new Set(paths)].sort(); if (slug) paths = paths.filter((path) => path.split("/").at(-2) === slug);
if (!paths.length) { console.error(`Nenhuma especificação encontrada${slug ? ` para o slug \`${slug}\`` : ""}. Crie \`specs/draft/<NNNN>-<slug>/spec.md\` com \`$specsfy-03-specify\`.`); process.exitCode = 2; }
else {
  const specs = [];
  for (const path of paths) { const text = await readFile(path, "utf8"); const field = (key, fallback = "Missing") => text.match(new RegExp(`^\\|\\s*${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\|\\s*(.+?)\\s*\\|\\s*$`, "im"))?.[1]?.trim() ?? fallback; const tasks = [...text.matchAll(/^- \[([ xX])\] (T\d{3,})\s+(.+?)[—-] Refs:\s*(.+?)\s+[—-] Depends:\s*(.+?)\s*$/gm)].map((match) => ({ complete: match[1].toLowerCase() === "x", id: match[2], depends: match[5].toLowerCase() === "none" ? [] : [...match[5].matchAll(/\bT\d{3,}\b/g)].map((item) => item[0]), checklist: [] })); const gates = { definition: field("Definition Gate"), plan: field("Plan Gate"), delivery: field("Delivery Gate") }; const done = new Set(tasks.filter((task) => task.complete).map((task) => task.id)); const ready = tasks.find((task) => !task.complete && task.depends.every((id) => done.has(id))); const next = ready?.checklist.find((item) => !item.complete); const blockers = []; if (field("Formato") !== "Specsfy/2.0") blockers.push("Formato deve ser Specsfy/2.0."); for (const [name, value] of Object.entries(gates)) if (["Failed", "Missing"].includes(value)) blockers.push(`${name[0].toUpperCase()}${name.slice(1)} Gate: ${value}.`); const status = field("Status", "Unknown"); const acts = { Draft: "Ato I — Definir", Defined: "Ato II — Projetar e provar", Planned: "Ato III — Entregar e validar", Implementing: "Ato III — Entregar e validar", Reviewing: "Ato III — Revisar e concluir", Complete: "Ato III — Entregar e validar" }; const nextSkills = { Draft: "specsfy-03-specify", Defined: "specsfy-05-tasks", Planned: "specsfy-07-implement", Implementing: "specsfy-07-implement", Reviewing: "specsfy-04-validate", Complete: null }; specs.push({ slug: field("Slug", path.split("/").at(-2)), path, status, effort: Number(field("Effort", "0")) || null, health: blockers.length ? "blocked" : status === "Complete" ? "complete" : "in_progress", act: acts[status] ?? "Unknown", next_skill: nextSkills[status] ?? null, gates, tasks: metric(done.size, tasks.length), checklists: metric(0, 0), ids: Object.fromEntries(["US", "FR", "NFR", "AC"].map((kind) => [kind, new Set([...text.matchAll(new RegExp(`\\b${kind}-\\d{3,}\\b`, "g"))].map((item) => item[0])).size])), blockers, next: next ? { task: ready.id, item: next.name, description: next.description, waiting_for: [] } : null }); }
  const summary = { total_specs: specs.length, complete_specs: specs.filter((spec) => spec.status === "Complete").length, gates: metric(specs.flatMap((spec) => Object.values(spec.gates)).filter((value) => value === "Passed").length, specs.length * 3), tasks: metric(specs.reduce((sum, spec) => sum + spec.tasks.complete, 0), specs.reduce((sum, spec) => sum + spec.tasks.total, 0)), checklists: metric(specs.reduce((sum, spec) => sum + spec.checklists.complete, 0), specs.reduce((sum, spec) => sum + spec.checklists.total, 0)), ids: Object.fromEntries(["US", "FR", "NFR", "AC"].map((kind) => [kind, specs.reduce((sum, spec) => sum + spec.ids[kind], 0)])), blockers: specs.reduce((sum, spec) => sum + spec.blockers.length, 0) }; const report = { root, summary, specs };
  if (json) console.log(JSON.stringify(report, null, 2)); else { console.log("Progresso geral"); console.log(`Especificações: ${summary.complete_specs}/${summary.total_specs} completas`); console.log(`Gates: ${summary.gates.complete}/${summary.gates.total} (${summary.gates.percent.toFixed(1)}%)`); console.log(`Tarefas: ${summary.tasks.complete}/${summary.tasks.total} (${summary.tasks.percent.toFixed(1)}%)`); console.log("\nPor especificação"); specs.forEach((spec) => console.log(`- ${spec.slug} [${spec.status}] | Effort: ${spec.effort ?? "?"}/10 | Próximo: ${spec.next ? `${spec.next.task}/${spec.next.item}` : "—"} | Handoff: ${spec.next_skill ? `$${spec.next_skill}` : "—"}`)); }
}
